### PR TITLE
fix problem when heading is 0

### PR DESCRIPTION
**Pull request by creniq**
RI-862

### CODE REVIEW

**Comment by jeremyqa** [comment]
how is this repo tested and released again?

**Comment by creniq** [comment]
> how is this repo tested and released again?

It is tested by building a new docker image for the affected components, then the docker image is tested locally and on dev.

**Comment by jeremyqa** [comment]
> > how is this repo tested and released again?
> 
> It is tested by building a new docker image for the affected components, then the docker image is tested locally and on dev.

So there's no automated testing or branch strategy? :(   Should I add this to my tech debt list?

**Comment by creniq** [comment]
> > > how is this repo tested and released again?
> > 
> > 
> > It is tested by building a new docker image for the affected components, then the docker image is tested locally and on dev.
> 
> So there's no automated testing or branch strategy? :( Should I add this to my tech debt list?

That's correct - no automated testing... And yes please add it to your list.

**Pull request merged**
